import { SearchResults } from "components/searchResults";
import type { GetStaticPropsContext, NextPage } from "next";
import Head from "next/head";
import { useProductsQuery } from "hooks";

const Search: NextPage = () => {
  const products = useProductsQuery();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div style={{ paddingTop: 84 }}>
        {products ? <SearchResults products={products} /> : <SearchResults />}
      </div>
    </div>
  );
};

export default Search;
