import { ProfileForm } from "components/profileForm";
import type { NextPage } from "next";
import Head from "next/head";

const Profile: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div style={{ paddingTop: 84 }}>
        <ProfileForm />
      </div>
    </div>
  );
};

export default Profile;
