import "styles/globals.css";
import type { AppProps } from "next/app";
import { Layout } from "components/layout";
import { RecoilRoot } from "recoil";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <RecoilRoot>
      <Layout>
        <Head>
          <title>Compralo</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='cart.ico' />
        </Head>
        <Component {...pageProps} />
      </Layout>
    </RecoilRoot>
  );
}

export default MyApp;
