import type { NextPage } from "next";
import Head from "next/head";
import { FeaturedProducts } from "components/featuredProducts";
import { Welcome } from "components/welcome";
import { apiCalls as api } from "lib/api";

const Home: NextPage = () => {
  api.test().then((r) => console.log(r));
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div style={{ paddingTop: 84 }}>
        <Welcome />
        <FeaturedProducts />
      </div>
    </div>
  );
};

export default Home;
