import { LoginForm } from "components/loginForm";
import { Signout } from "components/logout";
import { useTokenValue } from "hooks";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const Signin: NextPage = () => {
  const token = useTokenValue();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div style={{ paddingTop: 84 }}>
        {!token ? <LoginForm /> : <Signout />}
      </div>
    </div>
  );
};

export default Signin;
